sudo: required
services:
  - docker
language: python
install:
  - pip install -r requirements.txt
after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
