services:
  - docker
language: python
python:
  - "3.7"
install:
  - pip install -r requirements/dev.txt
script:
  - behave test/features/
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key:
    secure: $HEROKU_API_KEY
  app: python-flask-blog
  on:
    repo: Artemon-line/python-flask-blog
